#pragma once
enum request_type {
	WHOIS, REGISTER_AS, // Name server
	TICK_HAPPENED, DELAY, TIME, DELAY_UNTIL, SHUTDOWN, // Clock server
	QUERY_ACTIVE, QUERY_SPATIALS, QUERY_ARRIVAL, SEND_SENSORS,
	SET_SPEED, REVERSE, SWITCH_SWITCH, SWITCH_GET,
    GET_STOPPING_DISTANCE, SET_STOPPING_DISTANCE, GET_LAST_KNOWN_SENSOR,
    QUERY_ERROR // Trains server
};
