#!/usr/bin/expect

set bin [lindex $argv 0]
set elf [lindex $argv 1]
set log1 [lindex $argv 2]
set log2 [lindex $argv 3]

send_user "$log1\n"
send_user "$log2\n"

spawn ./scripts/qemu capture $bin $log1 $log2
set qemu_id $spawn_id

spawn arm-none-eabi-gdb -ex "target remote localhost:1234" -ex "b exited_main" -ex "c" -ex "set confirm off" -ex "q" $elf
wait

set spawn_id $qemu_id
send \003
wait
